#!/bin/bash

source build
source demo.env

function start(){
    start-db
    start-backend
}

function stop(){
    stop-backend
    stop-db
}

function restart(){
    stop
    start
}

function restart-backend(){
    stop-backend
    start-backend
}

function start-backend(){
    docker run --detach \
        --name "${BACKEND_NAME}" \
        -p 10001:10001 \
        -e MONGO_URI="mongodb://${MONGO_NAME}:27017" \
        -e URL_PROTOCOL=http \
        -e URL_SERVER=localhost \
        -e URL_PORT=10001 \
        -e URL_PATH= \
        ${BACKEND_IMAGE}
}

function start-db(){
    docker run --detach --name "${MONGO_NAME}" "${MONGO_IMAGE}"
}

function stop-backend(){
    docker stop "${BACKEND_NAME}"
    docker rm "${BACKEND_NAME}"
}

function stop-db(){
    docker stop "${MONGO_NAME}"
    docker rm "${MONGO_NAME}"
}

function logs(){
    echo "================ ${MONGO_NAME} ================"
    docker logs "${MONGO_NAME}"
    echo "================ ${MONGO_NAME} ================"
    echo
    echo "================ ${BACKEND_NAME} ================"
    docker logs "${BACKEND_NAME}"
    echo "================ ${BACKEND_NAME} ================"
}

# Run build if we were called (not sourced) from the command line.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]] ; then
    # Run the subcommand requested... for example `./demo restart` runs restart()
    "$@"
fi
