#!/bin/bash

# -e: Exit on first error.
# -u: Reading an undefined variable is an error.
set -eu

# Identify the directory containing this script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


# Rebuild and restart the SUT and its dependencies and then run the test-runner
# to test it.
function test-sut(){
    down                                            # stop and remove anything from a previous run
    docker-compose build                            # build all the images
    docker-compose up --detach backend              # start backend and its dependencies
    docker-compose run --rm test-runner             # run the tests
}


# Stop and remove containers, networks, and volumes created to support the
# testing environment described in docker-compose.yaml.
function down(){
    docker-compose down --remove-orphans --volumes  # stop and remove anything from a previous run
}


# Run npm. Use Docker so npm doesn't have to be installed locally.
function npm(){
    docker-compose -f "${DIR}/docker-compose.yaml" run --rm npm "$@"
}


# Push the image to the container registry.
# Requires a file named .env.gitlab.credentials that defines the following
# enviornment variables
#
#     USERNAME=
#     REGISTRY_ACCESS_TOKEN=
#
# Get the access token from GitLab.
function push-image(){
    source .env.gitlab.credentials
    docker login -u "${USERNAME}" -p "${REGISTRY_ACCESS_TOKEN}" registry.gitlab.com
    docker push registry.gitlab.com/librefoodpantry/training/spikeathons/winter-2021/stoney-manage-items/backend
}

# Run build if we were called (not sourced) from the command line.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]] ; then
    # Run the subcommand requested... for example `./demo restart` runs restart()
    "$@"
fi
