#!/bin/bash

# -e: Exit on first error.
# -u: Reading an undefined variable is an error.
set -eu

# Identify the directory containing this script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function test-sut(){
    down                                            # stop and remove anything from a previous run
    docker-compose build                            # build all the images
    docker-compose up --detach backend              # start backend and its dependencies
    docker-compose run --rm test-runner             # run the tests
}

function down(){
    docker-compose down --remove-orphans --volumes  # stop and remove anything from a previous run
}

function npm(){
    docker-compose -f "${DIR}/docker-compose.yaml" run --rm npm "$@"
}

# Run build if we were called (not sourced) from the command line.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]] ; then
    # Run the subcommand requested... for example `./demo restart` runs restart()
    "$@"
fi
