version: "3.3"
services:

  backend-server:
    image: registry.gitlab.com/librefoodpantry/training/spikeathons/winter-2021/stoney-manage-items/backend:latest
    ## init doesn't exist until docker-compose version 3.7
    ## but we are restricted to 3.3 by GitHub CI (for now)
    # init: true
    ports:
      - 10001:3000
    environment:
      HOST_BASE_URL: http://localhost:10001/v0
      MONGO_URI: mongodb://backend-database
    networks:
      - backend-network
    depends_on:
      - backend-database

  backend-database:
    image: mongo:4
    networks:
      - backend-network
    volumes:
      - type: bind
        source: ./backend-database
        target: /data/db

networks:
  backend-network:
