version: "3.3"
services:

  backend-server:
    image: backend-server
    build: .
    init: true
    ports:
      - 10001:3000
    environment:
      HOST_BASE_URL: http://localhost:10001/v0
      MONGO_URI: mongodb://backend-database
    networks:
      - backend-network
    depends_on:
      - backend-database

  backend-database:
    image: mongo:4
    networks:
      - backend-network

  test-runner:
    image: test-runner
    build: ./testing/test-runner
    environment:
      SUT_BASE_URL: http://backend-server:3000/v0
      SUT_MONGO_URL: mongodb://backend-database
      SUT_MONGO_DATABASE: items
      SUT_MONGO_COLLECTION: items
      TEST_TIMEOUT_MS: 5000
    volumes:
      - type: bind
        source: ./testing/tests
        target: /app/test
        read_only: true
      - type: bind
        source: ./src/openapi.yaml
        target: /openapi.yaml
        read_only: true
    networks:
      - backend-network
    depends_on:
      - backend-server

networks:
  backend-network:
