openapi: "3.0.2"
info:
  title: "Manage Items API"
  version: "0.1.0"
servers:
  - url: "http://localhost:3000"
paths:
  /items:
    get:
      responses:
        "200":
          description: "Items"
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        name:
                          type: string
