openapi: "3.0.3"
info:
  title: "Manage Items API"
  version: "0.1.0"

# Tags are not required, but are needed for OpenApiTools' openapi-generator-cli
# to generate appropriate controller and service files.
tags:
  - name: "Items"
  - name: "Generated"

paths:
  /items:
    get:
      operationId: listItems
      tags:
        - "Items"
        - "Generated"
      responses:
        "200":
          description: "List items."
          content:
            application/json:
              schema:
                type: object
                required:
                  - "items"
                properties:
                  items:
                    nullable: false
                    type: array
                    items:
                      type: object
                      required:
                        - "_id"
                        - "name"
                      properties:
                        _id:
                          type: string
                          description: "Unique identifier consisting of a 24 digit hexidecimal values (a MongoDB stingified ObjectID)"
                          nullable: false
                          minLength: 24
                          maxLength: 24
                          pattern: '^[a-zA-Z0-9]+$'
                          example: '0123456789aBcDeF01234567'
                        name:
                          type: string
                          description: "Name of the item."
                          nullable: false
                          minLength: 1
                          maxLength: 128
                          pattern: '\S+'
                          example: 'Canned of tuna'
