version: "3.3"
services:
  backend-server:
    image: backend-server:dev
    build: ../..
    # init: true
    ports:
      - 10001:3000
    environment:
      BASE_URL: http://localhost:10001/v0
      MONGO_URI: mongodb://backend-database
    networks:
      - backend-network
    depends_on:
      - backend-database

  backend-database:
    image: mongo:4
    networks:
      - backend-network

networks:
  backend-network:
