openapi: 3.0.3
info:
  title: Manage Items API
  version: 0.1.0
servers:
- url: /
tags:
- name: Items
paths:
  /items:
    get:
      operationId: listItems
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemArray'
          description: List items.
      tags:
      - Items
      x-eov-operation-handler: controllers/ItemsController
    post:
      operationId: createItem
      requestBody:
        content:
          application/json:
            examples:
              soup:
                value:
                  name: Soup
              tuna:
                value:
                  name: Tuna
              bread:
                value:
                  name: Bread
            schema:
              $ref: '#/components/schemas/ItemData'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: Created.
          headers:
            Location:
              description: URI of new item.
              explode: false
              required: true
              schema:
                minLength: 1
                nullable: false
                type: string
              style: simple
      tags:
      - Items
      x-eov-operation-handler: controllers/ItemsController
  /items/{_id}:
    get:
      operationId: getItem
      parameters:
      - explode: false
        in: path
        name: _id
        required: true
        schema:
          $ref: '#/components/schemas/Id'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: Item.
        "404":
          description: Item not found.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      tags:
      - Items
      x-eov-operation-handler: controllers/ItemsController
components:
  schemas:
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
    ItemData:
      example:
        name: Canned tuna
      properties:
        name:
          description: Name of the item.
          example: Canned tuna
          maxLength: 128
          minLength: 1
          nullable: false
          pattern: \S+
          type: string
      required:
      - name
      type: object
    ItemArray:
      items:
        $ref: '#/components/schemas/Item'
      nullable: false
      type: array
    Item:
      example:
        name: Canned tuna
        _id: 0123456789aBcDeF01234567
      properties:
        _id:
          description: Unique identifier consisting of a 24 digit hexidecimal values
            (a MongoDB stingified ObjectID)
          example: 0123456789aBcDeF01234567
          maxLength: 24
          minLength: 24
          nullable: false
          pattern: ^[a-zA-Z0-9]+$
          type: string
        name:
          description: Name of the item.
          example: Canned tuna
          maxLength: 128
          minLength: 1
          nullable: false
          pattern: \S+
          type: string
      required:
      - _id
      - name
      type: object
    Id:
      description: Unique identifier consisting of a 24 digit hexidecimal values (a
        MongoDB stingified ObjectID)
      example: 0123456789aBcDeF01234567
      maxLength: 24
      minLength: 24
      nullable: false
      pattern: ^[a-zA-Z0-9]+$
      type: string
    ItemName:
      description: Name of the item.
      example: Canned tuna
      maxLength: 128
      minLength: 1
      nullable: false
      pattern: \S+
      type: string
